[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apo2holo"
version = "0.0.1"
description = "Skript that allows to annotate the active site and iron-sulfur cofactors in NiFe Hydrogenases"
authors = [
    {name = "Jan-Niklas Forster"}
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.11"
keywords = ["bioinformatics", "hydrogenase", "annotation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "platformdirs==4.11.7",
    "biopython",
    "ase==3.29.0",
    "dscribe==2.1.2",
    "numpy",
    "pandas==3.0.5",
    "plotly==6.5.2",
    "pyhmmer==0.12.3",
    "PyYAML",
    "Requests",
    "scikit-learn==1.9.0",
    "scipy==1.17.1",
    "tqdm==4.67.3",
]

[project.scripts]
apo2holo = "apo2holo.cli:entry"

[project.urls]
Repository = "https://github.com/jan-fors/hydrogenase-apo2holo-annotations"

[tool.setuptools.packages.find]
where = ["."]
include = ["apo2holo*"]

[tool.setuptools.package-data]
apo2holo = ["config/*.yaml", "config/*.yml"]