[project]
name = "apo2holo"
version = "0.0.1"
description = "Skript that allows to annotate the active site and iron-sulfur cofactors in NiFe Hydrogenases"
authors = [
    {name = "Jan-Niklas Forster"}
]
license = "GNU"
readme = "README.md"
keywords = ["bioinformatics", "hydrogenase", "annotation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "platformdirs>=3.0",
    "ase==3.29.0",
    "Bio==1.8.3",
    "biopython==1.86",
    "dscribe==2.1.2",
    "numpy==2.5.2",
    "pandas==3.0.5",
    "platformdirs==4.11.7",
    "plotly==6.5.2",
    "pyhmmer==0.12.3",
    "PyYAML==6.0.3",
    "Requests==2.34.2",
    "scikit_learn==1.9.0",
    "scipy==1.18.1",
    "tqdm==4.67.3"

]

[project.scripts]
apo2holo = "apo2holo.cli:entry"

[project.urls]
Repository = "https://github.com/solarflip/hydrogenase-apo2holo-annotations"