verbose : yes # defined by user as well

models:
  active_site:
    path: null
    search_type: mc
  fes:
    pocket:
      path: null
      search_type: mc
    type:
      path: null
      search_type: mc
  
  # match inference fingerprint based on model
  # read model fingerprint radius for specific tasks from model yamls as default ONLY mention in config if not usual
  # search type as well


structure_db:
  path: null
  chain_dir: null
  nn_clustering_radius: 4.0
  FIDENT_THRESHOLD: 0.1
  BITS_THRESHOLD: 0
